# Generated by Django 2.2.10 on 2020-08-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userphoto',
            options={'verbose_name': 'Изображение пользователя', 'verbose_name_plural': 'Изображения пользователя'},
        ),
    ]
