# Generated by Django 2.2.10 on 2020-08-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0003_user_profile_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
