# Generated by Django 2.2.10 on 2020-08-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0004_auto_20200828_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='дата рождения'),
        ),
    ]
