# Generated by Django 2.2.10 on 2020-08-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0005_auto_20200828_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orientation',
            field=models.CharField(choices=[('heterosexual', 'гетеросексуальность'), ('homosexual', 'гомосексуальность'), ('bisexual', 'бисекусальность'), ('unknown', 'неизвестно')], default='unknown', max_length=32, verbose_name='ориентация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('man', 'мужской'), ('woman', 'женский'), ('unknown', 'неизвестно')], default='unknown', max_length=32, verbose_name='пол'),
        ),
    ]
