# Generated by Django 2.2.10 on 2020-09-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0007_usersconnect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('мужской', 'man'), ('женский', 'woman'), ('неизвестно', 'unknown')], default='неизвестно', max_length=32, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='orientation',
            field=models.CharField(choices=[('гетеросексуальность', 'heterosexual'), ('гомосексуальность', 'homosexual'), ('бисекусальность', 'bisexual'), ('неизвестно', 'unknown')], default='неизвестно', max_length=32, verbose_name='ориентация'),
        ),
    ]
