# Generated by Django 2.2.10 on 2020-09-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0009_auto_20200904_0105'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='matcha_tag',
        ),
    ]
