# Generated by Django 2.2.10 on 2020-09-22 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import matcha.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0015_usersblacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('лайк', 'like'), ('просмотр профиля', 'profile'), ('сообщение', 'message'), ('лайк в ответ', 'like back'), ('разрывание коннекта', 'ignore')], max_length=32, verbose_name='тип')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_1_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь 1')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_2_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь 2')),
            ],
            options={
                'verbose_name': 'Notification-коннект пользователей',
                'verbose_name_plural': 'Notification-коннекты пользователей',
            },
            bases=(matcha.models.ManagedModel, models.Model, matcha.models.GetById),
        ),
    ]
