# Generated by Django 2.2.10 on 2020-09-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersconnect',
            name='type',
            field=models.CharField(choices=[('плюс', 'plus'), ('минус', 'minus')], default='плюс', max_length=32, verbose_name='тип'),
        ),
    ]
