# Generated by Django 2.2.10 on 2020-09-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0017_usersconnect_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fake_accusations',
        ),
    ]
