# Generated by Django 2.2.10 on 2020-09-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0018_remove_user_fake_accusations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=64, null=True, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=64, null=True, verbose_name='страна'),
        ),
    ]
