# Generated by Django 2.2.10 on 2020-09-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0020_auto_20200923_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='was_read',
            field=models.BooleanField(default=False, verbose_name='оповещение прочитано'),
        ),
    ]
