# Generated by Django 2.2.10 on 2020-09-25 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import matcha.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0021_notification_was_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('1 -> 2', '1 -> 2'), ('2 -> 1', '2 -> 1')], max_length=32, verbose_name='тип')),
                ('message', models.CharField(max_length=256, verbose_name='сообщение')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message_1_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь 1')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message_2_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь 2')),
            ],
            options={
                'verbose_name': 'Message-коннект пользователей',
                'verbose_name_plural': 'Message-коннекты пользователей',
            },
            bases=(matcha.models.ManagedModel, models.Model, matcha.models.GetById),
        ),
    ]
