# Generated by Django 2.2.10 on 2020-12-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0022_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='рейтинг'),
        ),
    ]
