# Generated by Django 2.2.10 on 2021-01-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0024_usersrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(null=True, verbose_name='last_online'),
        ),
    ]
