# Generated by Django 2.2.10 on 2021-01-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0026_auto_20210114_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
