# Generated by Django 2.2.10 on 2021-01-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcha', '0028_user_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='modified',
        ),
    ]
